### ISSUE TITLE
Error occurred during running.

### ISSUE THREAD

**Issue by YanghangZheng-GDUT** [DanielTrosten/DeepMVC#4]
I found an error message when running: 
`Traceback (most recent call last):
  File "/home/code2/DeepMVC/src/hang_train.py", line 9, in <module> from models.build_model import build_model 
 File "/home/code2/DeepMVC/src/models/__init__.py", line 1, in <module>from .comvc import comvc, comvc_loss
  File "/home/code2/DeepMVC/src/models/comvc/comvc.py", line 3, in <module> from models.simvc.simvc import SiMVC
  File "/home/code2/DeepMVC/src/models/simvc/simvc.py", line 4, in <module> from models.clustering_module import get_clustering_module
  File "/home/code2/DeepMVC/src/models/clustering_module/__init__.py", line 2, in <module> from .hp_ddc import HPDDC

ModuleNotFoundError: No module named 'models.clustering_module.hp_ddc`

I look forward to your response and thank you in advance.

**Comment by zyxforever** [comment]
例汤好，这个问题是怎么解决的

**Comment by zyxforever** [comment]
您好，想知道这个问题是怎么解决的
